version: 2

models:
  - name: stg_databird_local_bike__brands
    description: "A comprehensive list of all brands represented in stores."
    columns:
      - name: brand_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: brand_name
        tests:
          - not_null
      

  - name: stg_databird_local_bike__categories
    description: "A comprehensive list of product categories"
    columns:
      - name: category_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: category_name
        tests:
          - not_null


  - name: stg_databird_local_bike__customers
    description: "List of all Local Bike customers"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  
  - name: stg_databird_local_bike__order_items
    description: "List of all items group by each order"
    columns:
      - name: order_item_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "One foreign key for this table"
        tests:
          - not_null
          - relationships:
              to: ref('stg_databird_local_bike__orders')
              field: order_id
      - name: product_id
        description: "One foreign key for this table"
        tests:
          - not_null
          - relationships:
              to: ref('stg_databird_local_bike__products')
              field: product_id
 

  - name: stg_databird_local_bike__orders
    description: "List of all purchases made by customers"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "One foreign key for this table"
        tests:
          - not_null
          - relationships:
              to: ref('stg_databird_local_bike__customers')
              field: customer_id
      - name: store_id
        description: "One foreign key for this table"
        tests:
          - not_null
          - relationships:
              to: ref('stg_databird_local_bike__stores')
              field: store_id
      - name: staff_id
        description: "One foreign key for this table"
        tests:
          - not_null
          - relationships:
              to: ref('stg_databird_local_bike__staffs')
              field: staff_id


  - name: stg_databird_local_bike__products
    description: "List of all products represented in stores."
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: brand_id
        description: "One foreign key for this table"
        tests:
          - not_null
          - relationships:
              to: ref('stg_databird_local_bike__brands')
              field: brand_id
      - name: category_id
        description: "One foreign key for this table"
        tests:
          - not_null
          - relationships:
              to: ref('stg_databird_local_bike__categories')
              field: category_id


  - name: stg_databird_local_bike__staffs
    description: "Each employee working in stores"
    columns:
      - name: staff_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: store_id
        description: "One foreign key for this table"
        tests:
          - not_null
          - relationships:
              to: ref('stg_databird_local_bike__stores')
              field: store_id
      - name: manager_id
        description: "One foreign key for this table with a relationship with staff_id in the same table. a staff may not have a manage (CEO for example)"
        tests:
          - relationships:
              to: ref('stg_databird_local_bike__staffs')
              field: staff_id


  - name: stg_databird_local_bike__stocks
    description: "List of stocks by product for each store."
    columns:
      - name: store_product_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: product_id
        description: "One foreign key for this table"
        tests:
          - not_null
          - relationships:
              to: ref('stg_databird_local_bike__products')
              field: product_id
      - name: store_id
        description: "One foreign key for this table"
        tests:
          - not_null
          - relationships:
              to: ref('stg_databird_local_bike__stores')
              field: store_id
 

  - name: stg_databird_local_bike__stores
    description: "List of Local Bike stores"
    columns:
      - name: store_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null